// Simple tool to dump the MSP registry to markdown (REGISTRY.md). Built as a helper executable.
#include <cstdio>
#include <string>
#include <vector>
#include <iomanip>
#include <iostream>
#include <fstream>
#include "transformer_msp_bridge/msp_registry.hpp"

using namespace transformer_msp_bridge;

int main(int argc, char** argv) {
  const char* out = (argc > 1) ? argv[1] : "REGISTRY.md";
  auto view = get_default_registry();
  std::ofstream ofs(out, std::ios::trunc);
  if (!ofs) {
    std::cerr << "Failed to open output file: " << out << "\n";
    return 1;
  }
  ofs << "# MSP Command Registry\n\n";
  ofs << "This file is generated by the build (registry_dump). Do not hand-edit; run the generation target if changes are made to msp_registry.cpp.\n\n";
  ofs << "| Index | ID (dec) | ID (hex) | Name | Default Rate (Hz) | Proto |\n";
  ofs << "|-------|----------|----------|------|-------------------|-------|\n";
  for (size_t i = 0; i < view.size; ++i) {
    const auto& d = view.data[i];
    ofs << "| " << i
        << " | " << d.id
        << " | 0x" << std::uppercase << std::hex << std::setw(4) << std::setfill('0') << d.id << std::dec
        << " | " << (d.name ? d.name : "<unnamed>")
        << " | " << d.poll_rate_hz
        << " | " << (d.is_v2() ? "V2" : "V1")
        << " |\n";
  }
  ofs << "\nTotal entries: " << view.size << "\n\n";
  ofs << "> Regenerate via: colcon build --packages-select transformer_msp_bridge && (cd build/transformer_msp_bridge && ./registry_dump ../../src/transformer_msp_bridge/REGISTRY.md)\n";
  return 0;
}
